BA_1000_4:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
BA_1000_5:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
BA_1000_6:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
BA_1000_7:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
BA_1000_8:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
BA_1000_9:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  knn: 3
  patience: 10
ER_1000_6:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001
  knn: 3
  patience: 10
PLC_1000_5_0.1:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 30
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001
  knn: 3
  patience: 10
WS_1000_8_0.8:
  model: DCRS
  seed: 319
  feature_type: 1
  fuse: 0.5
  num_feats: 32
  num_hidden: 32
  num_instances: 20
  gamma: 1
  Lossmean: True
  optimizer: Adam
  learning_rate: 0.0001
  weight_decay: 0.00001
  knn: 3
  patience: 10

